apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas:1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      initContainers:
        - name: init-mydb
          image: busybox:latest
          command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        - name: init-memcache
          image: busybox:latest
          command: ['sh', '-c', 'until nslookup vpromq01; do echo waiting for mymq; sleep 2; done;']
      containers:
        - name: vproapp
          image: virajdalave/vprofileapp:latest
          ports:
            - name: vproapp-port
              containerPort: 8080
          